### PR TITLE
Fixes #775 - Added anagram checker in python

### LINKED ISSUE #775: Issue - Creating Anagram Checker in Python
To add three different approaches in python to check whether the given strings are an anagram of one another.

### PR DESCRIPTION
**Pull request by nuhman**
Pull Request checklist - 

- [x] This pull request fixes #775 
- [x] The directory structure is of the form `is_anagram`
- [x] Don't duplicate stuff.

### CODE REVIEW

**Comment by PiyushPawar17** [comment]
@nuhman @t2013anurag - The `anagram(s1, s2)` function is too slow. It takes approximately 11 seconds for the input of string of length 10000 while [this](https://github.com/PiyushPawar17/programming/blob/f43d34155e04a83d64f24ebe103f78aea7f1149e/is_anagram/is_anagram.py) function takes approximately 0.005 seconds. Also, `anagram(s1, s2)` is case-insensitive.
screenshot 5

**Comment by PiyushPawar17** [comment]
@nuhman  @t2013anurag - The `anagram_1(s1, s2)` function works incorrectly. Given input `FFFFFFFFFF` for `s1` and `ddddddd` for `s2` the function returns `True` where it is supposed to return `False`.
screenshot 6

**Comment by PiyushPawar17** [comment]
@nuhman @t2013anurag - Also tried comparing `anagram_2(s1,s2)` with [this](https://github.com/PiyushPawar17/programming/blob/f43d34155e04a83d64f24ebe103f78aea7f1149e/is_anagram/is_anagram.py) for strings of length `10000000`. [This](https://github.com/PiyushPawar17/programming/blob/f43d34155e04a83d64f24ebe103f78aea7f1149e/is_anagram/is_anagram.py) is efficient.
screenshot 8

**Comment by nuhman** [comment]
@t2013anurag  @PiyushPawar17 Great find! Never thought I should put the **most** efficient code out there.  Your code is way cleaner and efficient.  Closing this PR.

**Pull request closed without merging**
