### PR TITLE
Added Totient Function in Python

### LINKED ISSUE #526: Creating Totient Function in Python

### PR DESCRIPTION
**Pull request by PiyushPawar17**
This pull request fixes #526

### CODE REVIEW

**Comment by t2013anurag** [comment]
@PiyushPawar17 - don't delete companies_rank

**Comment by PiyushPawar17** [comment]
I didn't deleted those.

**Comment by t2013anurag** [comment]
@PiyushPawar17 - I see 4 file changes.

https://github.com/hacktoberfest17/programming/pull/527/files

**Comment by t2013anurag** [comment]
@PiyushPawar17 rebase and push again or cherry-pick the commit.

**Comment by PiyushPawar17** [comment]
Ok

**Comment by t2013anurag** [comment]
@PiyushPawar17 I can still see those 3 files.

**Comment by t2013anurag** [comment]
The new commit didn't fix it.

**Comment by PiyushPawar17** [comment]
@t2013anurag  something's wrong. Should I send a new PR?

**Comment by t2013anurag** [comment]
@PiyushPawar17 yeah do that, I am closing this.

**Pull request closed without merging**
